import random

def gerar_palavra_secreta():
    palavras = ['âmbito', 'néscio', 'índole', 'exceto', 'vereda', 'convém', 'mister', 'alusão', 'inócuo', 'infame', 'anseio', 'apogeu', 'mérito', 'afável', 'exímio', 'pressa', 'facção', 'nocivo', 'aferir', 'apreço', 'escopo', 'júbilo', 'isento', 'adesão', 'adorno', 'paixão',
    'eficaz', 'alheio', 'idôneo', 'casual', 'lúdico', 'abster', 'receio', 'ciente', 'astuto', 'idiota', 'hábito', 'cômico', 'êxtase', 'dispor', 'sanção', 'sessão', 'formal', 'cessão', 'dúvida', 'ocioso', 'difuso', 'escusa', 'dádiva', 'alento', 'decoro', 'maroto', 'florão', 
    'solene', 'lograr', 'avidez', 'perene', 'ensejo', 'lírico', 'ênfase', 'utopia', 'ímpeto', 'gentil', 'legado', 'eximir', 'lábaro', 'lícito', 'coagir', 'alçada', 'rancor',  'glória', 'iníquo', 'função', 'faceta', 'ínfimo', 'emoção', 'patife', 'inepto', 'lacuna', 'relato', 
    'cortês', 'otário', 'alocar', 'inerte', 'coesão', 'julgar', 'outrem', 'aludir', 'sisudo', 'também', 'cobiça', 'remoto', 'tácito', 'herege', 'embora', 'vedado', 'prover', 'asseio', 'acento', 'método', 'altivo', 'pensar', 'encher', 'etéreo', 'objeto', 'buscar', 'compor', 
    'agonia', 'quanto', 'esteio', 'danado', 'acesso', 'exalar', 'sóbrio', 'aguçar', 'rotina', 'esboço', 'cético', 'desejo', 'avante', 'proeza', 'nativo', 'axioma', 'abjeto', 'vulgar', 'deixar', 'emitir', 'linear', 'adágio', 'adepto', 'cessar', 'arguir', 'apatia', 'elidir', 
    'passar', 'idílio', 'porfia', 'amiúde', 'insano', 'omisso', 'gitano', 'bênção', 'alarde', 'franco', 'polido', 'espaço', 'sereno', 'trazer', 'emanar', 'viagem', 'enxuto', 'suprir', 'cismar', 'acordo', 'origem', 'esvair', 'forjar', 'mártir', 'ilação', 'inibir',  'cínico', 
    'ancião', 'deriva', 'crença', 'jamais', 'menção', 'tríade', 'sentir', 'exílio', 'galgar', 'limiar', 'tópico', 'atraso', 'diante', 'prazer', 'evocar', 'servir', 'penhor', 'cingir', 'arrimo', 'súbito', 'início', 'vetado', 'ousado', 'bordão', 'sátira', 'sempre', 'hostil', 
    'esmero', 'feição', 'provém', 'fático', 'conter', 'inútil', 'cassar', 'ironia', 'chapéu', 'súdito', 'cólera', 'devido', 'brando', 'delito', 'estima', 'piegas', 'desdém', 'sádico', 'tornar', 'secção', 'coação', 'cerrar', 'aduzir', 'inveja', 'crível', 'nuance',
    'amanhã', 'limite', 'seguir', 'evadir', 'tirano', 'nômade', 'clamar', 'aderir', 'amável', 'onerar', 'motriz', 'léxico', 'cálido', 'exigir', 'comigo', 'lúcido', 'exíguo', 'escuso', 'várias', 'mítico', 'lavrar', 'pátria', 'pleito', 'embate', 'grande', 'clichê', 
    'fraude', 'teoria', 'loquaz', 'devoto', 'pueril', 'erigir', 'acatar', 'abismo', 'mazela', 'bélico', 'plebeu', 'férias', 'sabido', 'talvez', 'chiste', 'tímido', 'frisar', 'fulgor', 'torpor', 'engodo', 'tensão', 'íntimo', 'xingar', 'perfil', 'tratar', 'manter', 
    'ofício', 'gênero', 'gênese', 'dotado', 'célere', 'peleja', 'expiar', 'práxis', 'surgir', 'credor', 'prisma', 'mácula', 'colher', 'exibir', 'tolher', 'emenda', 'ofensa', 'formos', 'contém', 'pudico', 'elogio', 'mostra', 'adorar', 'estado', 'servil', 'ceifar', 
    'poente', 'divino', 'evasão', 'ilidir', 'dicção', 'coibir', 'pacato', 'omitir', 'rapina', 'propor', 'alguma', 'beleza', 'erário', 'inapto', 'sermos', 'acerca', 'índice', 'pessoa', 'aurora', 'quando', 'demais', 'prezar', 'aporte', 'querer', 'semear', 'prévio', 
    'arguto', 'voltar', 'dilema', 'obstar', 'agouro', 'vermos', 'abolir', 'ajudar', 'pairar', 'brecha', 'apesar', 'asceta', 'destra', 'despir', 'condiz', 'cativo', 'charco', 'aflige', 'jovial', 'lastro', 'flanco', 'padrão', 'álcool', 'abonar', 'arroio', 'saciar', 
    'apenas', 'porvir', 'oposto', 'findar', 'enlace', 'lisura', 'exação', 'ventre', 'acervo', 'gestão', 'colega', 'vileza', 'cuidar', 'aceder', 'ilusão', 'imagem', 'expert', 'enigma', 'cobrir', 'máximo', 'insumo', 'motivo', 'adular', 'velado', 'triste', 'sovina', 
    'roubar', 'saíram', 'burlar', 'nascer', 'severo', 'margem', 'ufanar', 'jiboia', 'primor', 'fastio', 'estará', 'pregar', 'imerso', 'prever', 'desuso', 'bonito', 'alegar', 'descer', 'missão', 'evitar', 'safado', 'perder', 'convir','social', 'condão', 'pranto', 
    'chofer', 'serrar', 'avesso', 'mandar', 'vieram', 'pesado', 'mestre', 'biltre', 'típico', 'viável', 'baleia', 'imolar', 'enfado', 'arauto', 'saguão', 'captar', 'grafar', 'jocoso', 'fértil',  'aflito', 'abstém', 'título', 'moroso', 'rápido', 'símile', 'purgar', 
    'fluido', 'obtuso', 'regalo', 'tutela', 'vexame', 'evento', 'perdão', 'sentar', 'tentar', 'regaço', 'quiser', 'nítido', 'frágil', 'trégua', 'remido', 'mentor', 'cediço', 'adotar', 'côvado', 'frugal', 'junção', 'arisco', 'reaver', 'cúmulo', 'bíblia', 'esfera', 
    'afinco', 'açoite', 'vítima', 'tarefa', 'máxima', 'primar', 'labuta', 'míngua', 'cartel', 'contar', 'porção', 'língua', 'lotado', 'romper', 'poupar', 'amante', 'antigo', 'imundo', 'balela', 'imoral', 'fulcro', 'afetar', 'agente', 'áspero', 'matriz', 'caução', 
    'sofrer', 'dentre', 'venham', 'ditoso', 'fausto', 'sustar', 'causar', 'munido', 'módulo', 'ciscar', 'larica', 'pseudo', 'zombar', 'ansiar', 'vários', 'começo', 'modelo', 'imenso', 'fálico', 'afoito', 'autuar', 'depois', 'trevas', 'efeito', 'melhor'  ]
    indice_aleatorio = random.randint(0, len(palavras) -1 )
    
    return palavras[indice_aleatorio]

