import random

def gerar_palavra_secreta():
    palavras = [
    'sagaz', 'âmago', 'negro', 'êxito', 'mexer', 'termo', 'senso', 'nobre', 'algoz', 'afeto', 'plena', 'ética', 'mútua', 'assaz', 
    'tênue', 'sutil', 'vigor', 'aquém', 'audaz', 'porém', 'fazer', 'sanar', 'seção', 'inato', 'assim', 'cerne', 'ideia', 'desde', 
    'fosse', 'poder', 'moral', 'torpe', 'honra', 'muito', 'justo', 'fútil', 'gozar', 'anexo', 'razão', 'gleba', 'orgia', 'comum', 
    'pesar', 'posse', 'ávido', 'então', 'boçal', 'dengo', 'genro', 'coser', 'ardil', 'porra', 'corja', 'prole', 'causa', 'pária', 
    'detém', 'dizer', 'tenaz', 'dever', 'digno', 'crivo', 'saber', 'óbice', 'ápice', 'ânsia', 'ceder', 'ânimo', 'brado', 'graça', 
    'fugaz', 'denso', 'valha', 'cozer', 'ainda', 'neném', 'vício', 'forte', 'estar', 'revés', 'vulgo', 'pudor', 'regra', 'dogma', 
    'louco', 'criar', 'banal', 'impor', 'pífio', 'tenro', 'desse', 'apraz', 'jeito', 'round', 'ordem', 'saúde', 'atrás', 'pedir', 
    'reaça', 'clava', 'mercê', 'viril', 'usura', 'juízo', 'sábio', 'prosa', 'manso', 'servo', 'ontem', 'seara',  'pauta', 'apego',
    'feliz', 'presa', 'coisa', 'falar', 'homem', 'cunho', 'forma', 'fluir', 'afago', 'devir', 'ébrio', 'meiga', 'platô', 'sério', 
    'vendo', 'xibiu', 'guisa', 'mesmo', 'pleno', 'limbo', 'temer', 'visar', 'mágoa', 'cisma', 'bruma', 'herói', 'acaso', 'puder', 
    'êxodo', 'lugar', 'valor', 'gerar', 'óbvio', 'afins', 'obter', 'ímpio', 'matiz', 'crise', 'praxe', 'amigo', 'casal', 'tempo', 
    'senil', 'certo', 'havia', 'vênia', 'fluxo', 'enfim', 'posso', 'ritmo', 'álibi', 'tédio', 'todos', 'tomar', 'garbo', 'reter', 
    'união', 'pulha', 'quiçá', 'etnia', 'sobre', 'ícone', 'tange', 'égide', 'sonho', 'lapso', 'mútuo', 'expor', 'haver', 'hábil', 
    'parvo', 'valia', 'abrir', 'visão', 'grato', 'vital', 'favor', 'vivaz', 'bravo', 'laico', 'fácil', 'parco', 'prumo', 'falso',
    'gênio', 'ameno', 'possa', 'olhar', 'reles', 'óbito', 'prime', 'burro', 'levar', 'tesão', 'tecer', 'casta', 'selar', 'anelo', 
    'fator', 'legal', 'ranço', 'citar', 'rogar', 'farsa', 'façam', 'adiar', 'noção', 'achar', 'coeso', 'grave', 'perda',  'messe', 
    'morte', 'cisão', 'falha', 'sarau', 'venha', 'passa', 'swing', 'briga', 'ateia', 'piada', 'tacha', 'conto', 'légua', 'farta', 
    'cargo', 'calmo', 'átimo', 'verde', 'perco', 'fruto', 'berro', 'plaga', 'busca', 'tarde', 'idoso', 'roupa', 'plumo', 'aviso', 
    'virar', 'vento', 'corso', 'chefe', 'tribo', 'broxa', 'arado', 'grama', 'assar', 'surto', 'estro', 'deram', 'troca', 'única', 
    'civil', 'seixo', 'recém', 'bruta', 'catre', 'traje', 'artur', 'ornar', 'saldo', 'ímpia', 'deste', 'nuvem', 'beijo', 'fosso', 
    'épico', 'cabal', 'sábia', 'nicho', 'imune', 'falta', 'fardo', 'sinto', 'ativo', 'força', 'gente', 'ouvir', 'exato', 'viver', 
    'haste', 'amplo', 'lavra', 'brega', 'sulco', 'sonso', 'passo', 'dúbio', 'noite', 'gesto', 'labor', 'cesta', 'revel', 'sesta', 
    'tendo', 'leigo', 'único', 'deter', 'vemos', 'árduo', 'atuar', 'feixe', 'rever', 'calma', 'vadia', 'ótica','atroz', 'culto', 
    'humor', 'ciúme', 'igual', 'tende', 'pobre', 'toada', 'hiato', 'sonsa', 'débil', 'ideal', 'ponto', 'vácuo', 'velho', 'outro', 
    'claro', 'ambos', 'terno', 'remir', 'fusão', 'varão', 'linda', 'carma', 'cauda', 'probo', 'leito', 'senão', 'advém', 'doido',
    'ajuda', 'marco', 'horda', 'jovem', 'fonte', 'inata', 'capaz', 'xeque', 'relva', 'tenra', 'algum', 'caçar','sendo', 'temor', 
    'botar', 'entre', 'frase', 'coçar', 'prece', 'cruel', 'massa', 'moção', 'vírus', 'morar', 'ambas', 'pouco', 'peste', 'coesa', 
    'beata', 'vulto', 'trama', 'houve', 'pegar', 'breve', 'birra', 'vasto', 'liame', 'manha', 'setor', 'adeus', 'salvo', 'senda', 
    'jazia', 'fruir', 'sinal', 'parar', 'treta', 'carro', 'puxar', 'séria', 'fugir', 'bando', 'nação', 'motim', 'gerir', 'prazo', 
    'virão', 'louça', 'pódio', 'rubro', 'lápis', 'crime', 'local', 'letal', 'hobby', 'pacto', 'ponha', 'folga', 'cover', 'cacho', 
    'ficar', 'velar', 'anuir', 'apoio', 'série', 'farão', 'terra', 'rigor', 'dorso', 'vimos', 'verso', 'vazio', 'líder', 'tanto',
    'refém', 'drama', 'brabo', 'hoste', 'aroma', 'vetar', 'vigia', 'fazia', 'pasmo', 'poema', 'feroz', 'açude', 'finjo', 'rival', 
    'andar', 'tosco', 'grupo', 'alude', 'leite', 'norma', 'sinhá', 'época', 'brava', 'rapaz', 'tenso', 'lenda', 'exame', 'arcar', 
    'ardor', 'seita', 'banzo', 'morro', 'blasé', 'nossa', 'pecha', 'átomo', 'visse', 'prado', 'livro', 'reger', 'antro', 'avaro', 
    'casto', 'sente', 'signo', 'fauna', 'covil', 'preso', 'faina', 'credo', 'minha', 'feito', 'furor', 'raiva', 'dócil', 'lazer', 
    'áureo', 'saída', 'ótimo', 'aliás', 'nunca', 'pajem', 'acima', 'junto', 'chulo', 'foder', 'mudar', 'fitar', 'opção', 'serão', 
    'móvel', 'mesma', 'troça', 'axila', 'monte', 'golpe', 'peito', 'ecoar', 'metiê', 'aluno', 'ávida', 'páreo', 'mundo', 'censo',
    'avião', 'ídolo', 'parte', 'venal', 'campo', 'tirar', 'soldo', 'reino', 'psico', 'malta', 'praga', 'quota', 'subir', 'chave', 
    'peixe', 'segue', 'comer', 'plano', 'prono', 'ocaso', 'meses', 'rezar', 'saiba', 'anciã', 'sorte', 'chuva', 'doído', 'prova', 
    'ímpar', 'vetor', 'ciclo', 'flora', 'torço', 'árido', 'maior', 'chata', 'aceso', 'brisa', 'papel', 'corno', 'acesa', 'verve',
    'supra', 'parca', 'verba', 'cioso', 'glosa', 'autor', 'lidar', 'jirau', 'mente', 'tinha', 'firme', 'grata', 'caixa', 'parva', 
    'coral', 'riste', 'lesse', 'fórum', 'plebe', 'lição', 'teste', 'daqui', 'súcia', 'forem', 'monge', 'clima', 'carta', 'chato', 
    'sumir', 'vilão', 'exijo', 'aonde', 'anais', 'logro', 'pompa', 'traga', 'corpo', 'preto', 'fixar', 'voraz', 'agora', 'antes', 
    'nível', 'apelo', 'ligar', 'pardo', 'tocar', 'fenda', 'trupe', 'átrio', 'lindo', 'retém', 'viria', 'sabia', 'dessa', 'alçar', 
    'coito', 'livre', 'navio', 'opaco', 'ficha', 'áurea', 'conta', 'fraco', 'ético', 'verbo', 'afora', 'astro', 'faixa', 'elite', 
    'oxalá', 'fatos', 'festa', 'magia', 'bater', 'calda', 'fatal', 'ébano', 'poeta', 'escol', 'cetro', 'macro', 'viram', 'júlia', 
    'privê', 'cousa', 'reses', 'junco', 'irmão', 'pique', 'deixa', 'molho', 'pagão', 'douto', 'salve', 'macio', 'abriu', 'turvo', 
    'torso', 'supor', 'atual', 'light', 'bicho', 'ígneo', 'asilo', 'posto', 'manhã', 'órfão', 'rouca', 'extra', 'caber', 'curso', 
    'judeu', 'sarça', 'sexta', 'locus', 'besta', 'vezes', 'ruína', 'desta', 'pisar', 'zelar', 'rádio', 'paira', 'texto', 'estão',
    'abuso', 'vídeo', 'ereto', 'finda', 'combo', 'porta', 'bioma', 'longe', 'vinha', 'culpa', 'agudo', 'cânon', 'feudo', 'vosso', 
    'menos', 'baixo', 'facto', 'tetra', 'urgia', 'advir', 'cútis', 'surja', 'bônus', 'meigo', 'estio', 'traço', 'drops', 'super', 
    'sítio', 'autos', 'tento', 'rumor', 'gosto', 'cocho', 'facho', 'suave', 'pilar', 'museu', 'clean', 'amena', 'árdua' 'pedra',
    'calão', 'lasso', 'turma', 'geral', 'acolá', 'optar', 'ações', 'medir', 'chama', 'pífia', 'nosso', 'boato', 'penta', 'mosto', 
    'bença', 'régio', 'manga', 'sósia', 'magna', 'vazão', 'tutor', 'rural', 'pavor', 'laudo', 'segar', 'tiver', 'bruto', 'perto', 
    'bucho', 'itens', 'renda', 'troco', 'mídia', 'tchau', 'nesse', 'vagar', 'molde', 'minar', 'jejum', 'odiar', 'lesto', 'viado', 
    'clero', 'amiga', 'vadio', 'inter', 'fossa', 'meche', 'feita', 'órgão', 'sótão', 'aviar', 'areia', 'pomar', 'rédea', 'anzol', 
    'negar', 'cenho', 'paiol', 'largo', 'cinto', 'ileso', 'lesão', 'canto', 'rocha', 'pugna', 'visto', 'horto', 'ruído', 'podar',
    'proto', 'bolsa', 'invés', 'pinho', 'urdir', 'marca', 'cível', 'vista', 'densa', 'ufano', 'frota', 'dúbia', 'guria', 'morfo',
    'mocho', 'jogar', 'vasta', 'penso', 'bulir', 'xucro', 'close', 'úmido', 'piche', 'culta', 'mamãe', 'peita', 'cardo', 'calvo', 
    'esgar', 'canil', 'bunda', 'cheia', 'chula', 'linha', 'resto', 'amada', 'apear', 'úbere', 'stand', 'varoa', 'misto', 'fazes', 
    'demão', 'natal', 'manto', 'monta', 'narco', 'findo', 'fundo', 'campa', 'barão', 'gemer', 'ágape', 'nessa', 'chaga', 'jazer', 
    'símio', 'tenha', 'retro', 'álbum', 'mover', 'preço', 'cerca', 'venho', 'folia', 'ardis', 'cosmo', 'lábia', 'punha', 'pólis', 
    'sabor', 'álamo', 'seiva', 'sigla', 'porca', 'velha', 'matar', 'calça', 'santo', 'banto', 'letra', 'ferpa', 'lento', 'todas', 
    'verão', 'volta', 'rente', 'louro', 'firma', 'ceita', 'salva', 'barro', 'arroz', 'etapa', 'tumba', 'axial', 'nesta', 'torna',
    'lutar', 'fugiu', 'zumbi', 'baixa', 'corar', 'queda', 'mimar', 'obtém', 'farol', 'coroa', 'cacto', 'veloz','mouro', 'sócio', 
    'redor', 'míope', 'limpo', 'trago', 'áudio', 'coevo', 'troço', 'bolso', 'enjoo', 'solta', 'ousar', 'final', 'sinta', 'lousa',
    'logos', 'neste', 'nácar', 'reler', 'fátuo', 'burra', 'folha', 'penca', 'longo', 'vário', 'vazia', 'dança', 'quite', 'forro',
    'macho', 'mania', 'farto', 'justa', 'sugar', 'puído', 'bedel', 'staff', 'ultra', 'repor', 'lucro', 'refil', 'viger', 'salmo', 
    'vedar', 'trato', 'arfar', 'depor', 'tição', 'porte', 'irado', 'grota', 'úteis', 'canso', 'âmbar', 'gíria', 'pasma', 'silvo'
    'gueto', 'passe', 'custo', 'calor', 'sexto', 'urgir', 'sadio', 'mimos', 'harém', 'hífen', 'valer', 'logia', 'versa', 'usual', 
    'quase', 'cheio', 'certa', 'risco', 'turva', 'nódoa', 'solto', 'cópia', 'praia', 'oásis', 'turba', 'filho', 'alado', 'índio', 
    'cifra', 'casar', 'bazar', 'gabar', 'mangá', 'amado' ]
    

    indice_aleatorio = random.randint(0, 997)
    return palavras[indice_aleatorio]